# WARNING - Generated by {fusen} from dev/flat_Lcross_pipeline.qmd: do not edit by hand # nolint: line_length_linter.

#' ann2ppp Read a h5ad file and convert it to a point process object from spatstat library
#' 
#' @param data_path path to the h5ad file
#' @param mask Optional: img object to be converted in the window of the point process class object
#' @param magnif level of magnification of the original H&E image, can be 20x or 40x
#' @param spat_coords_name names of coordinate of the centroids in the h5ad file
#' @param marks_col name of the .obs vector with the names of the marks (usually the cell types names)
#' @importFrom anndataR read_h5ad
#' @importFrom spatstat.geom owin affine ppp
#' @return An object of class "ppp"
#' @export
ann2ppp <- function(data_path, mask = NULL, magnif, spat_coords_name = c("x", "y"), marks_col = "type") {
  
  # magnif is the value of the magnification parameter in the metadata (can be 20 or 40 (20x or 40x respectively)) 
  # it's probably an error if it's noted as 20x.
  
  # 1. Read AnnData
  ann <- read_h5ad(data_path)
  
  # 2. Extract spatial coordinates
  spat <- ann$obsm$spatial
  x_coords <- spat[, 1]
  y_coords <- spat[, 2]
  
  # 3. Extract marks (e.g., cell types)
  marks_data <- NULL
  if (marks_col %in% colnames(ann$obs)) {
    marks_data <- as.factor(ann$obs[[marks_col]])
  }
  
  # 4. Define the window (owin)
  if (!is.null(mask)) {
    # Extract the 2D matrix from the imager cimg object (dropping z and c dimensions).
    # imager keeps 'x' as rows and 'y' as columns, but spatstat's owin mask 
    # expects 'y' as rows and 'x' as columns, so we transpose it.
    # We also convert it to a logical matrix (TRUE for foreground > 0)
    mask_mat <- t(mask[, , 1, 1] > 0.5) 

    # Create an owin using the image mask and the ranges of the spatial coordinates
    win_thumb <- owin(
      xrange = c(0, dim(mask)[1]), 
      yrange = c(0, dim(mask)[2]), 
      mask = mask_mat
    )
    # C. Calculate exact scale
    exact_scale <- magnif / 1.25
    
    # D. Transform the window in the full resolution scale of the coordinates
    final_win <- affine(win_thumb, mat = diag(c(exact_scale, exact_scale)))
    
  } else {
    # Create a basic bounding box window if no mask is provided
    final_win <- owin(
      xrange = range(x_coords, na.rm = TRUE), 
      yrange = range(y_coords, na.rm = TRUE)
    )
  }
  
  # 5. Build the PPP object
  p <- ppp(
    x = x_coords, 
    y = y_coords, 
    window = final_win,
    marks = marks_data
  )
  
  return(p)
}

