# WARNING - Generated by {fusen} from dev/flat_Lcross_pipeline.qmd: do not edit by hand # nolint: line_length_linter.

#' downsample_KDE Function to downsample based on the Kernel Density Estimation.
#' 
#' It needs a pp objects, the marks name which is a vector of dim 2 and a target number of point to which downsample. 
#' It's possible to personalized the density.ppp function
#' 
#' @param ppp_obj object of class "ppp" from spatstat
#' @param marks_name vector of dim 2 with the names of the cell types to apply the function to
#' @param n_target number of point in the ppp object to downsample
#' @param ... additional specification for the density.ppp function
#' @importFrom parallel mclapply detectCores
#' @importFrom spatstat.geom marks split.ppp npoints lookup.im coords superimpose marks<-
#' @importFrom spatstat.explore density.ppp bw.ppl
#' @return An object of class "ppp" with n_target points for each marks_name
#' @export
downsample_KDE <- function(ppp_obj, marks_name, n_target, ...) {
  
  # 1. Subset to the specified marks
  pp_neo <- subset(ppp_obj, marks %in% marks_name)
  marks(pp_neo) <- factor(marks(pp_neo))
  
  # 2. Split into a named list based on the marks
  pp_split <- split.ppp(pp_neo)
  
  # 3. Process each split in parallel
  sampled_list <- mclapply(pp_split, function(pp) {
    
    n_available <- npoints(pp)
    
    # Safely handle empty patterns
    if (n_available == 0) return(pp[integer(0)])
    
    # Skip KDE if we don't have enough points to downsample
    if (n_available <= n_target) return(pp)
    
    # Calculate KDE safely with error handling for bandwidth selection
    kern <- tryCatch({
      density.ppp(pp, at="pixels", ...)
    }, error = function(e) {
      # Fallback: if auto-bandwidth fails, try a simple rule or fixed sigma
      # Adjust or expose this fallback based on your data scale
      density.ppp(pp, at="pixels", sigma = bw.ppl(pp))
    })
    
    xy <- coords(pp)
    pint <- lookup.im(kern, xy$x, xy$y)
    
    good <- which(is.finite(pint) & !is.na(pint) & pint > 0)
    if (length(good) == 0) return(pp[integer(0)])
    if (length(good) <= n_target) return(pp[good])
    
    w <- 1 / pint[good]
    w <- w / sum(w)
    
    # Defensive programming: use a robust sampling wrapper to avoid the sample(x) gotcha
    sampled_idx <- if (length(good) == 1) good else sample(good, n_target, replace = FALSE, prob = w)
    
    return(pp[sampled_idx])
    
  }, mc.cores = min(length(pp_split), detectCores()))
  
  # 4. Recombine using the explicit geometry package namespace
  pp_final <- do.call(superimpose, sampled_list)
  
  return(pp_final)
}
