# WARNING - Generated by {fusen} from dev/flat_fda_pipeline.qmd: do not edit by hand # nolint: line_length_linter.

utils::globalVariables(c("r", "L_value", "L_plot_value", "Slide", "cluster"))

#' plot_smoothed_Lfun Function to plot the smoothed Lcross object
#' 
#' @param smoothed_obj list with elements "r", breaks vector, and "fd", object of the fd class
#' @param clusters_vec vector of cluster value for each sample
#' @param mark_i name of the mark value for which the Lcross function was calculated
#' @param mark_j name of the mark value for which the Lcross function was calculated
#' @param center_plot to choose if you want the plot centered (L-r ~ r) or not. 
#' @importFrom fda eval.fd
#' @importFrom tidyr pivot_longer
#' @importFrom dplyr mutate left_join
#' @importFrom ggplot2 ggplot geom_hline geom_line theme_minimal labs theme aes 
#' @importFrom utils globalVariables
#' @return A ggplot object
#' @export

plot_smoothed_Lfun <- function(smoothed_obj, clusters_vec, mark_i = "Mark 1", mark_j = "Mark 2", center_plot = TRUE) {
  
  # 1. Extract the distance vector (r)
  r_vec <- smoothed_obj$r
  
  # 2. Evaluate the functional data object (fd) to get smoothed values
  # This creates a matrix where rows are 'r' distances and columns are samples
  smooth_mat <- eval.fd(r_vec, smoothed_obj$fd)
  
  # 3. Convert the matrix to a data.frame and prepare for ggplot
  df_smooth <- as.data.frame(smooth_mat)
  df_smooth$r <- r_vec
  
  # Pivot to long format
  df_long <- pivot_longer(
    df_smooth,
    cols = -r,
    names_to = "Slide",
    values_to = "L_value"
  )
  
  # 4. Center the L-function (L(r) - r) if requested 
  # (Since you ran fsmooth with centered = FALSE, we can center it visually here)
  if (center_plot) {
    df_long <- df_long |> mutate(L_plot_value = L_value - r)
  } else {
    df_long <- df_long |> mutate(L_plot_value = L_value)
  }
  
  # 5. Prepare the cluster metadata from the named vector (memb_hc)
  cluster_df <- data.frame(
    Slide = names(clusters_vec),
    cluster = as.factor(clusters_vec)
  )
  
  # 6. Join the functional data with the cluster assignments
  df_final <- df_long |> 
    left_join(cluster_df, by = "Slide")
  
  # 7. Build the ggplot
  p <- ggplot(df_final, aes(x = r, y = L_plot_value, group = Slide, color = cluster)) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
    geom_line(alpha = 0.7, linewidth = 0.6) + 
    theme_minimal() +
    labs(
      title = paste0("Smoothed L-cross Function: ", mark_i, " vs ", mark_j),
      subtitle = ifelse(center_plot, 
                        "Centered L-function (L(r) - r). Positive = Attraction, Negative = Repulsion", 
                        "L-function L(r)"),
      x = "Radius (r)",
      y = ifelse(center_plot, "L(r) - r", "L(r)"),
      color = "Cluster"
    ) +
    theme(legend.position = "right")
  
  return(p)
}
